### ISSUE TITLE
User defined LazyTile interface change 

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/tiledarray#66]
I am working on changing my code to work with interface change introduced by commit 281bbf8b621acd05d9cd6309673c6f21f5c561b6. 

I got some error with LazyTile. 

Here is the old documentation about LazyTile interface.
```
class MyLazyTile {
public:
  typedef ... eval_type; // The data tile to which this tile will be converted to; typically TiledArray::Tensor
                         // Can instead define TiledArray::eval_trait<MyLazyTile>::type

  // Default constructor
  MyLazyTile();

  // Copy constructor
  MyLazyTile(const MyLazyTile& other);

  // Assignment operator
  MyLazyTile& operator=(const MyLazyTile& other);

  // Convert lazy tile to data tile
  operator eval_type() const;

  // MADNESS compliant serialization
  template <typename Archive>
  void serialize(const Archive&);

}; // class MyLazyTile
```

My old code follow this interface. However, when updating to code to work with the newest TiledArray, I got the following compiling error:

```
[ 96%] Building CXX object examples/CMakeFiles/simple_stored_df_scf.dir/simple_stored_df_scf.cpp.o
cd /Users/ChongPeng/Library/Caches/CLion12/cmake/generated/5d51773a/5d51773a/Debug1/examples && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -std=c++11 -std=c++11 -stdlib=libc++ -g -I/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include -I/usr/local/include/eigen3 -I/usr/local/include -I/Users/ChongPeng/Workspace/Development/install/libint_clang/include -I/Users/ChongPeng/Workspace/Development/install/libint_clang/include/libint2 -I/Users/ChongPeng/Workspace/Development/source/BTAS -I/usr/local/Cellar/rapidjson/1.0.2/include -I/Users/ChongPeng/Library/Caches/CLion12/cmake/generated/5d51773a/5d51773a/__default__1/include/cereal/src/cereal/include -I/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/PARENT_SCOPE    -o CMakeFiles/simple_stored_df_scf.dir/simple_stored_df_scf.cpp.o -c /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:5:
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../include/tiledarray.h:7:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/tiledarray.h:38:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/conversions/sparse_to_dense.h:29:
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/array.h:54:30: error: ambiguous partial specializations of 'numeric_type<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, void>'
    typedef typename detail::numeric_type<Tile>::type element_type; ///< The tile element type
                             ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../integrals/direct_tile.h:93:11: note: in instantiation of template class 'TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>' requested here
    Array array_;
          ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../scf/soad.h:150:18: note: in instantiation of template class 'mpqc::integrals::DirectArray<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough>, TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy> >' requested here
    auto eri_j = integrals::soad_direct_integrals(world, engs, bs_j);
                 ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:476:22: note: in instantiation of function template specialization 'mpqc::scf::fock_from_soad<std::__1::shared_ptr<mpqc::integrals::EnginePool<libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb> > >, TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, mpqc::integrals::TensorPassThrough>' requested here
              = scf::fock_from_soad(world, clustered_mol, basis, eri_e, H);
                     ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/type_traits.h:189:12: note: partial specialization matches [with T = mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >]
    struct numeric_type<T, typename std::enable_if<is_type<typename T::value_type>::value
           ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/type_traits.h:196:12: note: partial specialization matches [with T = mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >]
    struct numeric_type<T, typename std::enable_if<is_lazy_tile<T>::value
           ^
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:5:
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../include/tiledarray.h:7:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/tiledarray.h:38:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/conversions/sparse_to_dense.h:29:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/array.h:27:
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/array_impl.h:391:15: error: exception specification of overriding function is more lax than base version
      virtual ~ArrayImpl() { }
              ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/array.h:55:22: note: in instantiation of template class 'TiledArray::detail::ArrayImpl<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>' requested here
    typedef typename impl_type::trange_type trange_type; ///< Tile range type
                     ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../integrals/direct_tile.h:93:11: note: in instantiation of template class 'TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>' requested here
    Array array_;
          ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../scf/soad.h:150:18: note: in instantiation of template class 'mpqc::integrals::DirectArray<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough>, TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy> >' requested here
    auto eri_j = integrals::soad_direct_integrals(world, engs, bs_j);
                 ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:476:22: note: in instantiation of function template specialization 'mpqc::scf::fock_from_soad<std::__1::shared_ptr<mpqc::integrals::EnginePool<libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb> > >, TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, mpqc::integrals::TensorPassThrough>' requested here
              = scf::fock_from_soad(world, clustered_mol, basis, eri_e, H);
                     ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tensor_impl.h:76:15: note: overridden virtual function is here
      virtual ~TensorImpl() { }
              ^
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:27:
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../scf/soad.h:161:20: error: type 'mpqc::integrals::DirectArray<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough>, TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy> >' does not provide a call operator
        K("i,j") = eri_k("i,k,j,l") * D_min("k,l");
                   ^~~~~
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:476:22: note: in instantiation of function template specialization 'mpqc::scf::fock_from_soad<std::__1::shared_ptr<mpqc::integrals::EnginePool<libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb> > >, TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, mpqc::integrals::TensorPassThrough>' requested here
              = scf::fock_from_soad(world, clustered_mol, basis, eri_e, H);
                     ^
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:20:
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../integrals/integrals.h:15:
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../scf/../integrals/direct_task_integrals.h:75:35: error: no matching constructor for initialization of 'DArray<4UL, TileType, SpPolicy>' (aka 'TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>')
    DArray<N, TileType, SpPolicy> out(world, trange, shape, pmap);
                                  ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../scf/soad.h:150:29: note: in instantiation of function template specialization 'mpqc::integrals::soad_direct_integrals<libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, 4, mpqc::integrals::TensorPassThrough>' requested here
    auto eri_j = integrals::soad_direct_integrals(world, engs, bs_j);
                            ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:476:22: note: in instantiation of function template specialization 'mpqc::scf::fock_from_soad<std::__1::shared_ptr<mpqc::integrals::EnginePool<libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb> > >, TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, mpqc::integrals::TensorPassThrough>' requested here
              = scf::fock_from_soad(world, clustered_mol, basis, eri_e, H);
                     ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/array.h:197:5: note: candidate constructor not viable: no known conversion from 'const TiledArray::TiledRange' to 'const trange_type' (aka 'const int') for 2nd argument
    DistArray(World& world, const trange_type& trange, const shape_type& shape,
    ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/array.h:211:5: note: candidate constructor template not viable: requires 2 arguments, but 4 were provided
    DistArray(const DistArray_& other, Op&& op) :
    ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/array.h:183:5: note: candidate constructor not viable: requires at most 3 arguments, but 4 were provided
    DistArray(World& world, const trange_type& trange,
    ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/array.h:173:5: note: candidate constructor not viable: requires single argument 'other', but 4 arguments were provided
    DistArray(const DistArray_& other) : pimpl_(other.pimpl_) { }
    ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/array.h:167:5: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
    DistArray() : pimpl_() { }
    ^
4 errors generated.
```

Is there an interface change in LazyTile? Let me know if I was doing anything wrong here.

**Comment by justusc** [comment]
The lazy tile defines a `value_type`, which is not a part of the interface. However, it should not fail for this reason. Fix in coming.

**Comment by pchong90** [comment]
@justusc Thank you for the fix. I got another error which might related to this. 

consume function only take one argument but two are provided at `array_eval.h:91`.
```
[ 96%] Building CXX object examples/CMakeFiles/simple_stored_df_scf.dir/simple_stored_df_scf.cpp.o
cd /Users/ChongPeng/Library/Caches/CLion12/cmake/generated/5d51773a/5d51773a/Debug1/examples && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -std=c++11 -std=c++11 -stdlib=libc++ -g -I/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include -I/usr/local/include/eigen3 -I/usr/local/include -I/Users/ChongPeng/Workspace/Development/install/libint_clang/include -I/Users/ChongPeng/Workspace/Development/install/libint_clang/include/libint2 -I/Users/ChongPeng/Workspace/Development/source/BTAS -I/usr/local/Cellar/rapidjson/1.0.2/include -I/Users/ChongPeng/Library/Caches/CLion12/cmake/generated/5d51773a/5d51773a/__default__1/include/cereal/src/cereal/include -I/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/PARENT_SCOPE    -o CMakeFiles/simple_stored_df_scf.dir/simple_stored_df_scf.cpp.o -c /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:5:
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../include/tiledarray.h:7:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/tiledarray.h:37:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/tsr_expr.h:32:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/tsr_engine.h:29:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/leaf_engine.h:30:
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/array_eval.h:91:48: error: no matching member function for call to 'consume'
      operator eval_type() const { return op_->consume(tile_, consume_); }
                                          ~~~~~^~~~~~~
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:198:91: note: in instantiation of member function 'TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >::operator Tensor' requested here
      static typename eval_trait<Tile>::type convert_tile_task(const Tile& tile) { return tile; }
                                                                                          ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:229:32: note: in instantiation of function template specialization 'TiledArray::detail::Summa<TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::ContractReduce<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, double>, TiledArray::SparsePolicy>::convert_tile_task<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > > >' requested here
            & Summa_::template convert_tile_task<typename Arg::value_type>,
                               ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:253:33: note: in instantiation of function template specialization 'TiledArray::detail::Summa<TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::ContractReduce<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, double>, TiledArray::SparsePolicy>::get_tile<const TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy> >' requested here
            vec.emplace_back(i, get_tile(arg, index));
                                ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:271:9: note: in instantiation of function template specialization 'TiledArray::detail::Summa<TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::ContractReduce<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, double>, TiledArray::SparsePolicy>::get_vector<const TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, std::__1::pair<unsigned long, madness::Future<TiledArray::Tensor<double, Eigen::aligned_allocator<double> > > > >' requested here
        get_vector(left_, left_start_local_ + k, left_end_, left_stride_local_, col);
        ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:940:19: note: in instantiation of member function 'TiledArray::detail::Summa<TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::ContractReduce<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, double>, TiledArray::SparsePolicy>::get_col' requested here
          owner_->get_col(k, col_);
                  ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:978:46: note: (skipping 5 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
          world_.taskq.add(this, & StepTask::get_col, k, madness::TaskAttributes::hipri());
                                             ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/mult_engine.h:297:31: note: in instantiation of member function 'TiledArray::expressions::ContEngine<TiledArray::expressions::MultEngine<TiledArray::expressions::TsrEngine<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrEngine<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> > >::make_dist_eval' requested here
          return ContEngine_::make_dist_eval();
                              ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/expr.h:178:65: note: in instantiation of member function 'TiledArray::expressions::MultEngine<TiledArray::expressions::TsrEngine<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrEngine<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> >::make_dist_eval' requested here
        typename engine_type::dist_eval_type dist_eval = engine.make_dist_eval();
                                                                ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/tsr_expr.h:127:25: note: in instantiation of function template specialization 'TiledArray::expressions::Expr<TiledArray::expressions::MultExpr<TiledArray::expressions::TsrExpr<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrExpr<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> > >::eval_to<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true>' requested here
        other.derived().eval_to(*this);
                        ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../scf/soad.h:157:18: note: in instantiation of function template specialization 'TiledArray::expressions::TsrExpr<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true>::operator=<TiledArray::expressions::MultExpr<TiledArray::expressions::TsrExpr<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrExpr<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> > >' requested here
        J("i,j") = eri_j("i,j,k,l") * D_min("k,l");
                 ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:476:22: note: in instantiation of function template specialization 'mpqc::scf::fock_from_soad<std::__1::shared_ptr<mpqc::integrals::EnginePool<libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb> > >, TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, mpqc::integrals::TensorPassThrough>' requested here
              = scf::fock_from_soad(world, clustered_mol, basis, eri_e, H);
                     ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/unary_wrapper.h:224:15: note: candidate template ignored: disabled by 'enable_if' [with A = mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> > &]
              std::is_same<typename std::decay<A>::type, argument_type>::value &&
              ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/unary_wrapper.h:233:15: note: candidate template ignored: disabled by 'enable_if' [with A = mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> > &]
              std::is_same<typename std::decay<A>::type, argument_type>::value &&
              ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/unary_wrapper.h:206:19: note: candidate function template not viable: requires single argument 'arg', but 2 arguments were provided
      result_type consume(A&& arg) const {
                  ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/unary_wrapper.h:218:19: note: candidate function template not viable: requires single argument 'arg', but 2 arguments were provided
      result_type consume(A&& arg) const {
                  ^
1 error generated.
```

**Comment by justusc** [comment]
This is a different issue.

**Comment by justusc** [comment]
Give the latest push. The issue should be resolved.

**Comment by pchong90** [comment]
@justusc Thanks. I am still not able to compile the code. Here is the new compilation error. Maybe TCC code need to be updated. If you will be in office tomorrow we can talk then. 
```
[ 96%] Building CXX object examples/CMakeFiles/simple_stored_df_scf.dir/simple_stored_df_scf.cpp.o
cd /Users/ChongPeng/Library/Caches/CLion12/cmake/generated/5d51773a/5d51773a/Debug1/examples && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -std=c++11 -std=c++11 -stdlib=libc++ -g -I/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include -I/usr/local/include/eigen3 -I/usr/local/include -I/Users/ChongPeng/Workspace/Development/install/libint_clang/include -I/Users/ChongPeng/Workspace/Development/install/libint_clang/include/libint2 -I/Users/ChongPeng/Workspace/Development/source/BTAS -I/usr/local/Cellar/rapidjson/1.0.2/include -I/Users/ChongPeng/Library/Caches/CLion12/cmake/generated/5d51773a/5d51773a/__default__1/include/cereal/src/cereal/include -I/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/PARENT_SCOPE    -o CMakeFiles/simple_stored_df_scf.dir/simple_stored_df_scf.cpp.o -c /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:5:
In file included from /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../include/tiledarray.h:7:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/tiledarray.h:36:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/scal_expr.h:29:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/unary_expr.h:29:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/expr.h:35:
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/unary_wrapper.h:215:30: error: non-const lvalue reference to type 'argument_type' (aka 'TiledArray::Tensor<double, Eigen::aligned_allocator<double> >') cannot bind to a value of unrelated type 'mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >'
          return op_.consume(std::forward<A>(arg));
                             ^~~~~~~~~~~~~~~~~~~~
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/array_eval.h:91:48: note: in instantiation of function template specialization 'TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> >::consume<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> > &>' requested here
      operator eval_type() const { return op_->consume(tile_, consume_); }
                                               ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:198:91: note: in instantiation of member function 'TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >::operator Tensor' requested here
      static typename eval_trait<Tile>::type convert_tile_task(const Tile& tile) { return tile; }
                                                                                          ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:229:32: note: in instantiation of function template specialization 'TiledArray::detail::Summa<TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::ContractReduce<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, double>, TiledArray::SparsePolicy>::convert_tile_task<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > > >' requested here
            & Summa_::template convert_tile_task<typename Arg::value_type>,
                               ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:253:33: note: in instantiation of function template specialization 'TiledArray::detail::Summa<TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::ContractReduce<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, double>, TiledArray::SparsePolicy>::get_tile<const TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy> >' requested here
            vec.emplace_back(i, get_tile(arg, index));
                                ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:271:9: note: in instantiation of function template specialization 'TiledArray::detail::Summa<TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::ContractReduce<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, double>, TiledArray::SparsePolicy>::get_vector<const TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, std::__1::pair<unsigned long, madness::Future<TiledArray::Tensor<double, Eigen::aligned_allocator<double> > > > >' requested here
        get_vector(left_, left_start_local_ + k, left_end_, left_stride_local_, col);
        ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:940:19: note: (skipping 6 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
          owner_->get_col(k, col_);
                  ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/mult_engine.h:297:31: note: in instantiation of member function 'TiledArray::expressions::ContEngine<TiledArray::expressions::MultEngine<TiledArray::expressions::TsrEngine<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrEngine<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> > >::make_dist_eval' requested here
          return ContEngine_::make_dist_eval();
                              ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/expr.h:178:65: note: in instantiation of member function 'TiledArray::expressions::MultEngine<TiledArray::expressions::TsrEngine<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrEngine<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> >::make_dist_eval' requested here
        typename engine_type::dist_eval_type dist_eval = engine.make_dist_eval();
                                                                ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/tsr_expr.h:127:25: note: in instantiation of function template specialization 'TiledArray::expressions::Expr<TiledArray::expressions::MultExpr<TiledArray::expressions::TsrExpr<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrExpr<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> > >::eval_to<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true>' requested here
        other.derived().eval_to(*this);
                        ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../scf/soad.h:157:18: note: in instantiation of function template specialization 'TiledArray::expressions::TsrExpr<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true>::operator=<TiledArray::expressions::MultExpr<TiledArray::expressions::TsrExpr<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrExpr<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> > >' requested here
        J("i,j") = eri_j("i,j,k,l") * D_min("k,l");
                 ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:476:22: /Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:476:22: [0mnote: in instantiation of function template specialization 'mpqc::scf::fock_from_soad<std::__1::shared_ptr<mpqc::integrals::EnginePool<libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb> > >, TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, mpqc::integrals::TensorPassThrough>' requested here
              = scf::fock_from_soad(world, clustered_mol, basis, eri_e, H);
                     ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/noop.h:99:40: note: passing argument to parameter 'arg' here
    result_type consume(argument_type& arg) const {
                                       ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/noop.h:92:14: error: no matching function for call to 'eval'
      return Noop_::template eval<is_consumable>(arg);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/unary_wrapper.h:217:16: note: in instantiation of function template specialization 'TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true>::operator()<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> > &>' requested here
        return op_(std::forward<A>(arg));
               ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/array_eval.h:91:48: [0;1;30mnote: in instantiation of function template specialization 'TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> >::consume<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> > &>' requested here
      operator eval_type() const { return op_->consume(tile_, consume_); }
                                               ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:198:91: note: in instantiation of member function 'TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >::operator Tensor' requested here
      static typename eval_trait<Tile>::type convert_tile_task(const Tile& tile) { return tile; }
                                                                                          ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:229:32: note: in instantiation of function template specialization 'TiledArray::detail::Summa<TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::ContractReduce<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, double>, TiledArray::SparsePolicy>::convert_tile_task<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > > >' requested here
            & Summa_::template convert_tile_task<typename Arg::value_type>,
                               ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:253:33: note: in instantiation of function template specialization 'TiledArray::detail::Summa<TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy>, TiledArray::ContractReduce<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, double>, TiledArray::SparsePolicy>::get_tile<const TiledArray::detail::DistEval<TiledArray::detail::LazyArrayTile<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::detail::UnaryWrapper<TiledArray::Noop<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, true> > >, TiledArray::SparsePolicy> >' requested here
            vec.emplace_back(i, get_tile(arg, index));
                                ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/dist_eval/contraction_eval.h:271:9: note: (skipping 7 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
        get_vector(left_, left_start_local_ + k, left_end_, left_stride_local_, col);
        ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/mult_engine.h:297:31: note: in instantiation of member function 'TiledArray::expressions::ContEngine<TiledArray::expressions::MultEngine<TiledArray::expressions::TsrEngine<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrEngine<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> > >::make_dist_eval' requested here
          return ContEngine_::make_dist_eval();
                              ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/expr.h:178:65: note: in instantiation of member function 'TiledArray::expressions::MultEngine<TiledArray::expressions::TsrEngine<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrEngine<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> >::make_dist_eval' requested here
        typename engine_type::dist_eval_type dist_eval = engine.make_dist_eval();
                                                                ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/expressions/tsr_expr.h:127:25: note: in instantiation of function template specialization 'TiledArray::expressions::Expr<TiledArray::expressions::MultExpr<TiledArray::expressions::TsrExpr<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrExpr<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> > >::eval_to<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true>' requested here
        other.derived().eval_to(*this);
                        ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/../scf/soad.h:157:18: note: in instantiation of function template specialization 'TiledArray::expressions::TsrExpr<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true>::operator=<TiledArray::expressions::MultExpr<TiledArray::expressions::TsrExpr<TiledArray::DistArray<mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >, TiledArray::SparsePolicy>, true>, TiledArray::expressions::TsrExpr<TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, true> > >' requested here
        J("i,j") = eri_j("i,j,k,l") * D_min("k,l");
                 ^
/Users/ChongPeng/Workspace/Development/source/TileClusterChem_fork/examples/simple_stored_df_scf.cpp:476:22: note: in instantiation of function template specialization 'mpqc::scf::fock_from_soad<std::__1::shared_ptr<mpqc::integrals::EnginePool<libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb> > >, TiledArray::DistArray<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::SparsePolicy>, mpqc::integrals::TensorPassThrough>' requested here
              = scf::fock_from_soad(world, clustered_mol, basis, eri_e, H);
                     ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/noop.h:71:24: note: candidate function [with C = true, $1 = nullptr] not viable: no known conversion from 'mpqc::integrals::DirectTile<mpqc::integrals::IntegralBuilder<4, libint2::TwoBodyEngine<libint2::MultiplicativeSphericalTwoBodyKernel::Coulomb>, mpqc::integrals::TensorPassThrough> >' to 'TiledArray::Tensor<double, Eigen::aligned_allocator<double> > &' for 1st argument
    static result_type eval(Arg& arg) { return arg; }
                       ^
/Users/ChongPeng/Workspace/Development/install/tiledarray_release_clang/include/TiledArray/tile_op/noop.h:64:47: note: candidate template ignored: disabled by 'enable_if' [with C = true]
    template <bool C, typename std::enable_if<!C>::type* = nullptr>
                                              ^
2 errors generated.
make[3]: *** [examples/CMakeFiles/simple_stored_df_scf.dir/simple_stored_df_scf.cpp.o] Error 1
make[2]: *** [examples/CMakeFiles/simple_stored_df_scf.dir/all] Error 2
make[1]: *** [examples/CMakeFiles/simple_stored_df_scf.dir/rule] Error 2
make: *** [simple_stored_df_scf] Error 2
```
